gerencia/urls.py
from django.urls import path
from .views import inicio_gerencia, listagem_noticia,cadastrar_noticia,editar_noticia, criar_categoria, editar_categoria, excluir_categoria, filtro_categoria

app_name = 'gerencia'

urlpatterns = [
    path('', inicio_gerencia, name='gerencia_inicial'),
    path('noticias/', listagem_noticia, name='listagem_noticia'),
    path('noticias/cadastro', cadastrar_noticia, name='cadastro_noticia'),
    path('noticias/editar/<int:id>', editar_noticia, name='editar_noticia'),
    path('cadastro_categoria/', criar_categoria, name='cadastro_categoria'),
    path('editar_categoria/<int:id>', editar_categoria, name='editar_categoria'),
    path('excluir_categoria/<int:id>', excluir_categoria, name='excluir_categoria'),
    path('filtro_categoria/', filtro_categoria, name='filtro_categoria'),
    # Add your URL patterns here
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from curso import views
from django.conf import settings
from django.conf.urls.static import static
from gerencia.views import index
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index,name='index' ), # index
    path('usuario/',include('usuarios.urls')),
    path('gerencia/',include('gerencia.urls')),
    path('curso/<int:curso_id>',views.detalhe_curso,name='detalhe_curso'),
    path('sobre/',views.pagina_sobre,name='pagina_sobre'),
    path('teste/',views.pagina_teste,name='pagina_teste'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Blog - Ifrn Pau dos Ferros</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #009739;">

            <div class="container">
                <a class="navbar-brand" href="#!">Blog IFRN-PDF</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link" href="#">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="#!">About</a></li>
                        <li class="nav-item"><a class="nav-link" href="#!">Contact</a></li>
                        <li class="nav-item"><a class="nav-link" aria-current="page" href="{% url 'gerencia:gerencia_inicial' %}">Gerência</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page header with logo and tagline-->
        <header class="py-5 bg-light border-bottom mb-4">
            <div class="container">
                <div class="text-center my-5">
                    <h1 class="fw-bolder">Bem-vindo ao Blog do IFRN-PDF</h1>
                    <p class="lead mb-0">Blog com as novidades e notícias do nosso campus.</p>
                </div>
            </div>
        </header>
        <!-- Page content-->
        <div class="container">
           {% block parte_central %}
           
           {% endblock %}
        </div>
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2023</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>